<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/GrpcDemo.proto

namespace GrpcDemo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GrpcDemo.HiReply</code>
 */
class HiReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.GrpcDemo.HiUser user = 2;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *     @type \GrpcDemo\HiUser $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\GrpcDemo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GrpcDemo.HiUser user = 2;</code>
     * @return \GrpcDemo\HiUser|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.GrpcDemo.HiUser user = 2;</code>
     * @param \GrpcDemo\HiUser $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \GrpcDemo\HiUser::class);
        $this->user = $var;

        return $this;
    }

}

